# Generated by Django 4.1.7 on 2023-03-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSSchemaFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.IntegerField(choices=[(0, "Повне ім'я"), (1, 'Робота'), (2, 'Email'), (3, "Ім'я домену"), (4, 'Номер телефону'), (5, 'Назва компанії'), (6, 'Текст'), (7, 'Число'), (8, 'Адреса'), (9, 'Дата')])),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('range_min', models.IntegerField(blank=True, null=True)),
                ('range_max', models.IntegerField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.fakecvsschema')),
            ],
        ),
    ]
