# Generated by Django 4.1.7 on 2023-03-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_cvsschemafields_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsschemafields',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cvsschemafields',
            name='range_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvsschemafields',
            name='range_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
