# Generated by Django 4.1.7 on 2023-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_cvsschemafields_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakecvsschema',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Кома(,)'), (';', 'Крапка з комою(;)'), ('\t', 'Табуляція(\\t)'), (' ', "Пробіл(' ')"), ('|', "Вертикальна палочка('|')")], default=',', max_length=1),
        ),
    ]
