# Generated by Django 4.1.7 on 2023-03-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_fakecvsschema_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsschemafields',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
