# Generated by Django 4.1.7 on 2023-03-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_cvsschemafields_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakecvsschema',
            name='delimiter',
        ),
    ]
