# Generated by Django 4.1.7 on 2023-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_fakecvsschema_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsschemafields',
            name='range_max',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='cvsschemafields',
            name='range_min',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
