# Generated by Django 4.1.7 on 2023-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_cvsschemafields_range_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakecvsschema',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Кома(,)'), (';', 'Крапка з комою(;)'), ('\t', 'Табуляція(\\t)'), (' ', "Пробіл(' ')"), ('|', "Вертикальна палочка('|')")], default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='fakecvsschema',
            name='quote_char',
            field=models.CharField(choices=[("''", "Одинарні лапки('')"), ('""', 'Подвійні лапки("")')], default="''", max_length=2),
        ),
    ]
