# Generated by Django 4.1.7 on 2023-03-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_fakecvsschema_delimiter_fakecvsschema_quote_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakecvsschema',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Кома(,)'), (';', 'Крапка з комою(;)'), ('\t', 'Табуляція(\\t)'), (' ', "Пробіл(' ')"), ('|', "Вертикальна палочка('|')")], default=',', max_length=2),
        ),
        migrations.AlterField(
            model_name='fakecvsschema',
            name='title',
            field=models.CharField(default='Untitled Schema', max_length=50),
        ),
    ]
