# Generated by Django 4.1.7 on 2023-03-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_fakecvsschema_quote_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakecvsschema',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Кома(,)'), (';', 'Крапка з комою(;)'), (' ', "Пробіл(' ')"), ('|', "Вертикальна палочка('|')")], default=',', max_length=2),
        ),
    ]
